"use client";

import { Activity, Database, Plus, Save, Settings, ShieldCheck, Trash2, Users } from "lucide-react";
import { useState } from "react";
import type { AppCatalogs, AppSettings, AppUser, AuditEntry, UserRole } from "@/lib/types";

type Tab="catalogs"|"users"|"settings"|"audit";
export default function AdminScreen({catalogs,onCatalogs,users,onUsers,settings,onSettings,audit}:{catalogs:AppCatalogs;onCatalogs:(c:AppCatalogs)=>void;users:AppUser[];onUsers:(u:AppUser[])=>void;settings:AppSettings;onSettings:(s:AppSettings)=>void;audit:AuditEntry[]}){
  const [tab,setTab]=useState<Tab>("catalogs");
  const [draft,setDraft]=useState(settings);const [newItem,setNewItem]=useState("");const [category,setCategory]=useState("Clientes");
  const [showUserForm,setShowUserForm]=useState(false);const [newUser,setNewUser]=useState({name:"",username:"",password:"",role:"Operario" as UserRole});
  return <><section className="page-heading"><div><div className="eyebrow"><i/> Gobierno y configuración</div><h1>Administración</h1><p>Catálogos, usuarios, roles, parámetros y registro de auditoría.</p></div></section><section className="admin-layout"><aside className="admin-nav"><button className={tab==="catalogs"?"active":""} onClick={()=>setTab("catalogs")}><Database size={17}/>Catálogos</button><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}><Users size={17}/>Usuarios y roles</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}><Settings size={17}/>Configuraciones</button><button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}><Activity size={17}/>Auditoría</button></aside><div className="admin-content panel">
    {tab==="catalogs"?<><div className="admin-head"><div><h2>Catálogos maestros</h2><p>Valores disponibles para filtros y solicitudes.</p></div></div><div className="catalog-tabs">{Object.keys(catalogs).map(c=><button className={category===c?"active":""} key={c} onClick={()=>setCategory(c)}>{c}<span>{catalogs[c].length}</span></button>)}</div><div className="catalog-add"><input value={newItem} onChange={e=>setNewItem(e.target.value)} placeholder={`Nuevo valor en ${category}`}/><button className="primary compact" onClick={()=>{if(!newItem.trim())return;onCatalogs({...catalogs,[category]:[...catalogs[category],newItem.trim()]});setNewItem("");}}><Plus size={15}/>Agregar</button></div><div className="catalog-list">{catalogs[category].map(item=><div key={item}><span>{item}</span><button onClick={()=>onCatalogs({...catalogs,[category]:catalogs[category].filter(v=>v!==item)})}><Trash2 size={14}/></button></div>)}</div></>:null}
    {tab==="users"?<><div className="admin-head"><div><h2>Usuarios y permisos</h2><p>Usuarios internos, contraseñas y roles.</p></div><button className="secondary" onClick={()=>setShowUserForm(value=>!value)}><Plus size={15}/>Nuevo usuario</button></div>{showUserForm?<div className="user-add"><input placeholder="Nombre" value={newUser.name} onChange={e=>setNewUser({...newUser,name:e.target.value})}/><input placeholder="Usuario" value={newUser.username} onChange={e=>setNewUser({...newUser,username:e.target.value})}/><input type="password" placeholder="Contraseña" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/><select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value as UserRole})}><option>Administrador</option><option>Supervisor</option><option>Operario</option></select><button className="primary compact" onClick={async()=>{if(!newUser.name.trim()||!newUser.username.trim()||!newUser.password||users.some(user=>user.username.toLowerCase()===newUser.username.trim().toLowerCase()))return;onUsers([...users,{id:crypto.randomUUID(),name:newUser.name.trim(),email:`${newUser.username.trim()}@bodega.local`,username:newUser.username.trim(),credentialHash:await hashPassword(newUser.password),role:newUser.role,active:true}]);setNewUser({name:"",username:"",password:"",role:"Operario"});setShowUserForm(false);}}><Plus size={14}/>Agregar</button></div>:null}<div className="user-table">{users.map(u=><div key={u.id}><div className="avatar">{u.name.slice(0,2).toUpperCase()}</div><span><strong>{u.name}</strong><small>@{u.username}</small></span><select value={u.role} disabled={u.username==="admin"} onChange={e=>onUsers(users.map(v=>v.id===u.id?{...v,role:e.target.value as UserRole}:v))}><option>Administrador</option><option>Supervisor</option><option>Operario</option></select><label className="switch"><input type="checkbox" checked={u.active} disabled={u.username==="admin"} onChange={e=>onUsers(users.map(v=>v.id===u.id?{...v,active:e.target.checked}:v))}/><i/></label><button className="delete-user" disabled={u.username==="admin"} title="Eliminar usuario" onClick={()=>onUsers(users.filter(v=>v.id!==u.id))}><Trash2 size={14}/></button></div>)}</div><div className="role-cards">{[["Administrador","Acceso total, configuración y usuarios"],["Supervisor","Importa, genera y consulta historial"],["Operario","Consulta estibas y genera borradores"]].map(([r,d])=><div key={r}><ShieldCheck size={18}/><strong>{r}</strong><small>{d}</small></div>)}</div></>:null}
    {tab==="settings"?<><div className="admin-head"><div><h2>Parámetros operativos</h2><p>La lógica se administra sin modificar código.</p></div></div><div className="settings-grid"><Field label="Días hasta vencimiento"><input type="number" value={draft.expirationDays} onChange={e=>setDraft({...draft,expirationDays:Number(e.target.value)})}/><small>Actualmente: exactamente 90 días</small></Field><Field label="Alerta urgente"><input type="number" value={draft.urgentDays} onChange={e=>setDraft({...draft,urgentDays:Number(e.target.value)})}/><small>Menos de 15 días</small></Field><Field label="Alerta preventiva"><input type="number" value={draft.warningDays} onChange={e=>setDraft({...draft,warningDays:Number(e.target.value)})}/><small>Menos de 30 días</small></Field><Field label="ID de Google Sheets"><input value={draft.spreadsheetId} onChange={e=>setDraft({...draft,spreadsheetId:e.target.value})}/></Field><Field label="GID inicial"><input value={draft.spreadsheetGid} onChange={e=>setDraft({...draft,spreadsheetGid:e.target.value})}/></Field><Field label="Modo de integración"><select value={draft.googleMode} onChange={e=>setDraft({...draft,googleMode:e.target.value as AppSettings["googleMode"]})}><option value="simulation">Simulación</option><option value="connected">Conectado</option></select></Field></div><div className="settings-actions"><button className="primary" onClick={()=>onSettings(draft)}><Save size={16}/>Guardar configuración</button></div></>:null}
    {tab==="audit"?<><div className="admin-head"><div><h2>Registro de auditoría</h2><p>Acciones relevantes con fecha, usuario y detalle.</p></div></div><div className="audit-list">{audit.map(a=><div key={a.id}><span className="audit-icon"><Activity size={15}/></span><div><strong>{a.action} · {a.entity}</strong><p>{a.detail}</p></div><aside><strong>{a.actor}</strong><small>{new Date(a.timestamp).toLocaleString("es-AR")}</small></aside></div>)}</div></>:null}
  </div></section></>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="setting-field"><span>{label}</span>{children}</label>}
async function hashPassword(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
