"use client";

import { AlertTriangle, Check, ChevronRight, FileDown, FileSpreadsheet, Printer, Search, Sparkles, Wine } from "lucide-react";
import { useMemo, useState } from "react";
import { exportVeExcel, exportVePdf } from "@/lib/exporters";
import { allocateFefo, groupAllocationsByLot, stockGroupKey } from "@/lib/allocations";
import { formatDate } from "@/lib/expiry";
import type { EvaluatedStack, ProductionOrder, VeRequest } from "@/lib/types";

type Props = {
  orders: ProductionOrder[]; activeOrder: ProductionOrder | null; onOrder: (order: ProductionOrder | null) => void;
  stacks: EvaluatedStack[]; selected: Set<string>; onSelected: (ids: Set<string>) => void;
  onGenerate: (request: VeRequest) => void; onGoStacks: () => void;
};

function today() { return new Date().toISOString().slice(0,10); }
const isUsable = (stack: EvaluatedStack) => stack.availableQuantity > 0 && ["under15", "under30", "ok"].includes(stack.expiryStatus);
const isInStock = (stack: EvaluatedStack) => stack.availableQuantity > 0;

export default function VeScreen({orders,activeOrder,onOrder,stacks,selected,onSelected,onGenerate,onGoStacks}:Props) {
  const [query,setQuery]=useState(""); const [stackQuery,setStackQuery]=useState("");const [showAll,setShowAll]=useState(false);const [alcohol,setAlcohol]=useState(activeOrder?.alcohol ?? "");const [observed,setObserved]=useState(false);
  const [requestDate,setRequestDate]=useState(today()); const [generated,setGenerated]=useState<VeRequest|null>(null);
  const selectedStacks=stacks.filter(s=>selected.has(s.id)&&isUsable(s));
  const recommendationPool=useMemo(()=>{
    if(!activeOrder)return stacks.filter(isInStock).slice(0,8);
    const variety=activeOrder.variety.toLowerCase(); const brand=activeOrder.brand.toLowerCase().split(" ")[0];
    const q=stackQuery.trim().toLowerCase();
    return stacks.filter(isInStock).filter(s=>!q||[s.barcode,s.pallet,s.productCode,s.product,s.variety,s.lot,s.cut].join(" ").toLowerCase().includes(q)).map(s=>({s,score:(s.variety&&variety.includes(s.variety.toLowerCase())?4:0)+(s.product.toLowerCase().includes(brand)?3:0)+(s.cut===activeOrder.cut?2:0)})).sort((a,b)=>b.score-a.score||(a.s.daysRemaining??9999)-(b.s.daysRemaining??9999)).map(v=>v.s);
  },[activeOrder,stacks,stackQuery]);
  const stockGroups=useMemo(()=>{const groups=new Map<string,EvaluatedStack[]>();recommendationPool.forEach(stack=>{const key=stockGroupKey(stack.productCode,stack.lot,stack.elaborationDate,stack.product,stack.cut);groups.set(key,[...(groups.get(key)??[]),stack]);});return [...groups.values()];},[recommendationPool]);
  const recommendations=stockGroups.slice(0,showAll?50:12);
  const totalStock=selectedStacks.reduce((n,s)=>n+s.availableQuantity,0);
  const allocations=activeOrder?allocateFefo(selectedStacks,activeOrder.bottles):[];
  const lotGroups=groupAllocationsByLot(allocations);
  const draft:VeRequest|null=activeOrder?{id:generated?.id??`draft-${activeOrder.id}`,number:generated?.number??"BORRADOR",createdAt:`${requestDate}T00:00:00.000Z`,requestDate,fillingDate:lotGroups[0]?.fillingDate??"",possibleDressingDate:activeOrder.possibleDressingDate,line:activeOrder.line,brand:activeOrder.brand,variety:activeOrder.variety,harvest:activeOrder.harvest,cut:activeOrder.cut||selectedStacks[0]?.cut||"",lots:lotGroups.map(group=>group.lot),selectedStackIds:selectedStacks.map(s=>s.id),totalStockBottles:totalStock,requestedBottles:activeOrder.bottles,productCode:activeOrder.internalCode,presentation:activeOrder.presentation,market:activeOrder.market,requestedBoxes:activeOrder.boxes,unitsPerBox:activeOrder.unitsPerBox,client:activeOrder.client,pn:activeOrder.pn,destination:activeOrder.country,closure:activeOrder.closure,alcohol,responsible:"",observed,allocations,status:"generated"}:null;
  const chooseGroup=(members:EvaluatedStack[])=>{const usable=members.filter(isUsable);const next=new Set(selected);const allSelected=usable.length>0&&usable.every(item=>next.has(item.id));usable.forEach(item=>allSelected?next.delete(item.id):next.add(item.id));onSelected(next);};
  const canGenerate=Boolean(draft&&selectedStacks.length&&activeOrder);
  const autoAssign=()=>{if(!activeOrder)return;const brand=activeOrder.brand.toLowerCase().split(" ")[0];const variety=activeOrder.variety.toLowerCase();let remaining=activeOrder.bottles;const ids=new Set<string>();for(const members of stockGroups){const sample=members[0];if(!(sample.product.toLowerCase().includes(brand)||(sample.variety&&variety.includes(sample.variety.toLowerCase()))))continue;members.forEach(item=>ids.add(item.id));remaining-=members.reduce((n,item)=>n+item.availableQuantity,0);if(remaining<=0)break;}onSelected(ids);};
  const generate=()=>{if(!draft||!canGenerate)return;const final={...draft,id:crypto.randomUUID(),number:`VE-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,createdAt:new Date().toISOString()};setGenerated(final);onGenerate(final);};

  if(!activeOrder)return <><section className="page-heading"><div><div className="eyebrow"><i/> Generación documental</div><h1>Nueva Solicitud VE</h1><p>Seleccione un producto VESTIR del programa para tomar PIN°, código, cliente, cajas y botellas.</p></div></section><section className="panel order-picker"><label className="filter-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por PIN°, marca, cliente o destino…"/></label><div className="order-choice-grid">{orders.filter(o=>o.action.trim().toUpperCase()==="VESTIR"&&[o.pn,o.internalCode,o.brand,o.client,o.country].join(" ").toLowerCase().includes(query.toLowerCase())).map(o=><button key={o.id} onClick={()=>onOrder(o)}><span>{o.week} · {o.line}</span><strong>{o.brand} · {o.variety}</strong><small>{o.pn} · {o.client} · {o.country}</small><div><b>{o.bottles.toLocaleString("es-AR")} botellas</b><ChevronRight size={16}/></div></button>)}</div></section></>;

  return <><section className="page-heading"><div><div className="eyebrow"><i/> Generación documental</div><h1>Nueva Solicitud VE</h1><p>Pedido {activeOrder.pn} · {activeOrder.client}</p></div><div className="heading-actions"><button className="secondary" onClick={()=>onOrder(null)}><FileSpreadsheet size={17}/> Cambiar pedido</button>{draft?<button className="primary" onClick={generate} disabled={!canGenerate}><Sparkles size={17}/> Generar y guardar</button>:null}</div></section>
    <div className="ve-layout"><div className="ve-main">
      <section className="panel form-panel"><div className="step-title"><span>1</span><div><strong>Datos del programa</strong><small>Tomados desde PIN° hasta Botellas de la fila VESTIR seleccionada.</small></div></div><div className="form-grid"><Field label="Fecha de solicitud"><input type="date" value={requestDate} onChange={e=>setRequestDate(e.target.value)}/></Field><Field label="Fecha de llenado por lote"><input value={lotGroups.length?lotGroups.map(group=>`${group.lot}: ${formatDate(group.fillingDate)}`).join(" · "):"Se calcula al asignar estibas"} readOnly/></Field><Field label="Fecha posible de vestido"><input value={formatDate(activeOrder.possibleDressingDate)} readOnly/></Field><Field label="Línea de producción"><input value={activeOrder.line} readOnly/></Field><Field label="Marca"><input value={activeOrder.brand} readOnly/></Field><Field label="Variedad"><input value={activeOrder.variety} readOnly/></Field><Field label="Cosecha"><input value={activeOrder.harvest} readOnly/></Field><Field label="Corte del reporte"><input value={activeOrder.cut||selectedStacks[0]?.cut||"Se completa al elegir estiba"} readOnly/></Field><Field label="Alcohol etiqueta"><input value={alcohol} onChange={e=>setAlcohol(e.target.value)}/></Field><Field label="Estiba observada"><select value={observed?"si":"no"} onChange={e=>setObserved(e.target.value==="si")}><option value="no">No</option><option value="si">Sí</option></select></Field></div></section>
      <section className="panel recommendation-panel"><div className="step-title"><span>2</span><div><strong>Asignar stock del reporte</strong><small>Se agrupan todos los CB con igual producto, lote y fecha de llenado; FEFO agota el grupo antes de pasar al siguiente.</small></div></div><div className="stock-source"><label className="order-search"><Search size={15}/><input value={stackQuery} onChange={e=>setStackQuery(e.target.value)} placeholder="Buscar producto, código, lote, corte o pallet…"/></label><button className="primary" onClick={autoAssign}><Sparkles size={15}/> Asignar por FEFO</button><button className="secondary" onClick={()=>setShowAll(value=>!value)}>{showAll?"Ver recomendadas":"Ver todo el stock"}</button><button className="secondary" onClick={onGoStacks}><FileSpreadsheet size={15}/> Actualizar reporte</button></div><div className="recommendation-list">{recommendations.map((members,i)=>{const s=members[0];const total=members.reduce((n,item)=>n+item.availableQuantity,0);const checked=members.every(item=>selected.has(item.id));return <label key={stockGroupKey(s.productCode,s.lot,s.elaborationDate)} className={checked?"recommendation selected":"recommendation"}><input type="checkbox" checked={checked} onChange={()=>chooseGroup(members)}/><span className="rank">{String(i+1).padStart(2,"0")}</span><div><strong>{s.product}</strong><small>{s.productCode} · {s.lot} · {formatDate(s.elaborationDate)} · {members.length} CB agrupados</small></div><div><strong>{total.toLocaleString("es-AR")}</strong><small>stock total</small></div><span className={`status ${s.expiryStatus}`}><i/>{s.daysRemaining??"—"} días</span></label>})}</div>{lotGroups.length?<div className="allocation-breakdown"><strong>Distribución del pedido</strong>{lotGroups.map(group=><div key={stockGroupKey(group.productCode,group.lot,group.fillingDate)}><span>{group.productCode} · Lote {group.lot} · Corte {group.cut||"—"}</span><b>{group.usedBottles.toLocaleString("es-AR")} botellas</b></div>)}<small>El Excel generará una hoja independiente por combinación de producto, lote y fecha.</small></div>:null}</section>
    </div><aside className="ve-side"><section className="selection-card"><div className="selection-head"><Wine size={20}/><div><strong>Resumen de la solicitud</strong><small>{selectedStacks.length} estibas habilitadas</small></div></div><dl><div><dt>Cliente</dt><dd>{activeOrder.client}</dd></div><div><dt>Destino</dt><dd>{activeOrder.country}</dd></div><div><dt>PN</dt><dd>{activeOrder.pn}</dd></div><div><dt>Presentación</dt><dd>{activeOrder.presentation}</dd></div><div><dt>Cierre</dt><dd>{activeOrder.closure||"—"}</dd></div><div><dt>Pedido</dt><dd>{activeOrder.bottles.toLocaleString("es-AR")} botellas</dd></div><div><dt>Stock seleccionado</dt><dd>{totalStock.toLocaleString("es-AR")} botellas</dd></div></dl>{selectedStacks.length===0?<div className="inline-warning"><AlertTriangle size={15}/>Seleccione al menos una estiba habilitada.</div>:totalStock<activeOrder.bottles?<div className="inline-warning"><AlertTriangle size={15}/>Stock incompleto: faltan {(activeOrder.bottles-totalStock).toLocaleString("es-AR")} botellas. Puede generar igualmente y completar con estibas de la semana.</div>:<div className="inline-ok"><Check size={15}/>Stock suficiente para el pedido.</div>}
        <button className="primary full" onClick={generate} disabled={!canGenerate}><Sparkles size={17}/> Generar Solicitud VE</button></section>
      {generated?<section className="generated-card"><div><Check size={18}/><span><strong>{generated.number}</strong><small>Guardada en el historial</small></span></div><button onClick={()=>void exportVeExcel(generated)}><FileSpreadsheet size={15}/> Excel</button><button onClick={()=>void exportVePdf(generated)}><FileDown size={15}/> PDF</button><button onClick={()=>window.print()}><Printer size={15}/> Imprimir</button></section>:null}</aside></div>
    {generated?<VePreview request={generated}/>:null}
  </>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>}
function VePreview({request}:{request:VeRequest}){const boxes=request.requestedBoxes??Math.ceil(request.requestedBottles/Math.max(1,request.unitsPerBox??1));return <section className="ve-preview-wrap"><div className="preview-toolbar"><div><strong>Vista previa del documento</strong><small>Basada en R1 IB 03 · Rev. 07</small></div><div><button onClick={()=>void exportVeExcel(request)}><FileSpreadsheet size={15}/> Excel</button><button onClick={()=>void exportVePdf(request)}><FileDown size={15}/> PDF</button><button onClick={()=>window.print()}><Printer size={15}/> Imprimir</button></div></div><div className="ve-document"><header><span>BODEGAS ESMERALDA S.A.</span><h2>SOLICITUD DE VESTIDO DE VINOS EN ESTIBA</h2><div><b>R1 IB 03</b><b>Rev. 07</b></div></header><section>{[["FECHA DE SOLICITUD",request.requestDate],["FECHA DE LLENADO",request.fillingDate],["FECHA POSIBLE DE VESTIDO",request.possibleDressingDate],["LÍNEA DE PRODUCTO",request.brand],["VARIEDAD / COSECHA",`${request.variety} · ${request.harvest}`],["Nº DE CORTE / LOTE",`${request.cut} · ${request.lots.join(" / ")}`],["BOTELLAS EN ESTIBA / SE OCUPAN",`${request.totalStockBottles.toLocaleString("es-AR")} / ${request.requestedBottles.toLocaleString("es-AR")}`],["CÓDIGO / PRESENTACIÓN",`${request.productCode} · ${request.presentation}`],[request.market.toLowerCase().includes("interno")?"MERCADO INTERNO · CAJAS":`MERCADO EXTERNO · ${request.unitsPerBox} UNIDADES`,boxes.toLocaleString("es-AR")],["CLIENTE / PN / DESTINO",`${request.client} · ${request.pn} · ${request.destination}`],["ALCOHOL ETIQUETA",request.alcohol],["ESTIBA OBSERVADA",request.observed?"X Sí · No":"Sí · X No"],["RESPONSABLE",""]].map(([l,v])=><div key={l}><b>{l}:</b><span>{v}</span></div>)}</section>{["LABORATORIO · ANÁLISIS","LEGALES · ANÁLISIS QUÍMICO / ALÉRGENOS","ENÓLOGO · DEGUSTACIÓN"].map(t=><div className="document-section" key={t}><strong>{t}</strong><i/><i/></div>)}</div></section>}
